name = "AlignedSpans"
uuid = "72438786-fd5d-49ef-8843-650acbdfe662"
authors = ["Beacon Biosignals, Inc."]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
TimeSpans = "bb34ddd2-327f-4c4a-bfb0-c98fc494ece1"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
